"""Build the literature links: System One models propose, Claude judges.

Step 1 (--candidates). Every decision-model run under <run>/runs/<folder>/
read some papers paragraph by paragraph (scripts/judge_paragraphs.py). A link
is a candidate for a paper when at least --min-readers of the readers that read
that paper found it there (a hosted reader only reads CC BY papers, so for the
rest the local readers must agree among themselves). Candidates go to
<run>/candidates.json with the paragraphs that produced them.

Step 2 (default). Claude reads each candidate's paragraphs and answers
supports / partial / not_stated with a verbatim quote (scripts/claude_judge.py),
three times. A link is kept when at least two of the three answers say
supports or partial and the quote is word for word in a paragraph. The rest go
to `not_added`, the review list, with the reason. The result is written to
config/relation_excerpts.yaml, from which scripts/build_relations.py generates
the links in config/relations.yaml.

Usage::

    python scripts/assemble_links.py --run extraction/<run> --readers jev=jev-1.13.0 winnow=winnow_e4b kev=kev-4b --candidates
    python scripts/claude_judge.py --run extraction/<run>
    python scripts/assemble_links.py --run extraction/<run> --readers ...           # write the excerpts
    python scripts/assemble_links.py --run extraction/<run> --readers ... --check   # fail if stale
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from exposome_ehr import decision as D  # noqa: E402
from exposome_ehr.config import load_vocabulary  # noqa: E402

OUT = ROOT / "config/relation_excerpts.yaml"
REPEATS = 3
HEADER = """\
# Source excerpts for the exposome evidence graph: the input the literature links are built from.
#
# Generated by scripts/assemble_links.py from the stored readers and judge; do not edit.
# Every link in relations.yaml that rests on the literature is generated from
# this file by scripts/build_relations.py. Taxonomy (is_a) edges are structure,
# not literature claims, and are not here.
#
# How a link gets here: System One models propose, Claude judges.
#   1. Decision models answer four typed questions for every paragraph
#      (scripts/judge_paragraphs.py). A link is a candidate for a paper when at
#      least {min_readers} of the models that read the paper found it there.
#   2. Claude reads the candidate's paragraphs and answers supports / partial /
#      not_stated with a verbatim quote, {repeats} times. A link is kept when a
#      majority confirm it and the quote is word for word in the paragraph.
# `paper` is the PMID; `note` names the readers and paragraphs and the judge's tally.
# Run: {run}. Readers: {readers}.
"""


def load_reader(folder: Path) -> dict[str, list[dict]]:
    return {p.stem: [json.loads(line) for line in p.read_text().splitlines() if line.strip()]
            for p in sorted(folder.glob("*.jsonl"))}


def found_by(run: Path, readers: dict[str, str], vocab) -> tuple[dict, dict]:
    """(paper -> edge -> reader -> paragraph ids, paper -> readers that read it)."""
    out: dict = {}
    read: dict[str, list[str]] = {}
    for name, folder in readers.items():
        for paper, recs in load_reader(run / "runs" / folder).items():
            read.setdefault(paper, []).append(name)
            for r in recs:
                for e in D.cascade(r, vocab):
                    out.setdefault(paper, {}).setdefault(e, {}).setdefault(name, []).append(r["id"].split(":")[1])
    return out, read


def candidates(run: Path, readers: dict[str, str], min_readers: int, vocab) -> list[dict]:
    fb, read = found_by(run, readers, vocab)
    out = []
    for paper in sorted(read, key=lambda k: (not k.isdigit(), k.zfill(12))):
        need = min(min_readers, len(read[paper]))
        for e, by in sorted(fb.get(paper, {}).items()):
            if len(by) < need:
                continue
            cnt = Counter(p for ps in by.values() for p in set(ps))
            paras = sorted(cnt, key=lambda p: (-cnt[p], p))[:3]
            out.append({"id": f"{paper}-{len(out) + 1:04d}", "paper": paper, "edge": list(e), "paragraphs": paras,
                        "readers": {n: sorted(set(ps)) for n, ps in by.items()}, "readers_available": read[paper]})
    return out


def verdicts(run: Path, cid: str) -> list[dict]:
    out = []
    for r in range(1, REPEATS + 1):
        f = run / "judge" / f"r{r}" / f"{cid}.json"
        if f.exists():
            meta = json.loads(f.with_suffix(".meta.json").read_text())
            out.append(json.loads(f.read_text()) | {"quote_check": meta["quote_check"]})
    return out


def q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def ev_line(ev: dict) -> str:
    parts = [f"paper: '{ev['paper']}'", f"verdict: {ev['verdict']}", f"section: {q(ev['section'])}"]
    if ev.get("quote"):
        parts.append(f"\n         quote: {q(ev['quote'])}")
    parts.append(f"\n         note: {q(ev['note'])}")
    return "      - {" + ", ".join(parts) + "}"


def assemble(run: Path, readers: dict[str, str], min_readers: int, vocab) -> tuple[str, dict]:
    cands = json.loads((run / "candidates.json").read_text())["candidates"]
    order = list(D.link_predicates(vocab))
    links: dict[tuple, list[dict]] = {}
    review: dict[tuple, dict] = {}
    stats: Counter = Counter()
    sections: dict[str, str] = {}
    manifest = run / "paragraphs.tsv"
    for line in manifest.read_text().splitlines()[1:]:
        cols = line.split("\t")
        sections[cols[0]] = cols[4] if len(cols) > 4 else ""
    for c in cands:
        e = tuple(c["edge"])
        vs = verdicts(run, c["id"])
        if len(vs) < REPEATS:
            raise SystemExit(f"{c['id']}: {len(vs)} of {REPEATS} judge answers stored; run scripts/claude_judge.py")
        yes = [v for v in vs if v["verdict"] in ("supports", "partial") and v["quote_check"] in ("exact", "spacing")]
        found = "; ".join(f"{n} ({', '.join(ps)})" for n, ps in c["readers"].items())
        judged = ", ".join(f"{k} {n}/{REPEATS}" for k, n in Counter(v["verdict"] for v in vs).most_common())
        if len(yes) * 2 > REPEATS:
            best = Counter(v["quote"] for v in yes).most_common(1)[0][0]
            v = next(x for x in yes if x["quote"] == best)
            pid = c["paragraphs"][v["passage"] - 1] if 1 <= v["passage"] <= len(c["paragraphs"]) else c["paragraphs"][0]
            verdict = "supports" if sum(x["verdict"] == "supports" for x in yes) * 2 > REPEATS else "partial"
            links.setdefault(e, []).append({"paper": c["paper"], "verdict": verdict,
                                            "section": sections.get(f"{c['paper']}:{pid}", ""), "quote": best,
                                            "note": f"Found by {found}. Claude judged: {judged}."})
            stats["kept"] += 1
        else:
            confirmed = sum(v["verdict"] in ("supports", "partial") for v in vs) * 2 > REPEATS
            why = ("The readers found it and Claude confirmed it, but Claude's quote is not word for word in the paragraph."
                   if confirmed else "The readers found it, but Claude judged that the paragraphs do not state it.")
            review.setdefault(e, {"reason": why, "evidence": []})["evidence"].append(
                {"paper": c["paper"], "verdict": "partial",
                 "section": sections.get(f"{c['paper']}:{c['paragraphs'][0]}", ""),
                 "note": f"Found by {found}. Claude judged: {judged}. {vs[0]['reason']}"})
            stats["not_confirmed"] += 1

    def key(k):
        return (order.index(k[1]) if k[1] in order else 99, k[0], k[2])

    lines = [HEADER.format(min_readers=min_readers, repeats=REPEATS, run=run.relative_to(ROOT) if run.is_relative_to(ROOT) else run,
                           readers=", ".join(f"{n} ({f})" for n, f in readers.items())), "\nexcerpts:\n"]
    for k in sorted(links, key=key):
        lines.append(f"\n  - edge: [{', '.join(k)}]\n    evidence:\n" + "\n".join(ev_line(ev) for ev in links[k]) + "\n")
    lines.append("\nnot_added:\n")
    for k in sorted(review, key=key):
        r = review[k]
        lines.append(f"\n  - edge: [{', '.join(k)}]\n    reason: {q(r['reason'])}\n    evidence:\n"
                     + "\n".join(ev_line(ev) for ev in r["evidence"]) + "\n")
    stats["links"], stats["review"] = len(links), len(review)
    return "".join(lines), dict(stats)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run", type=Path, required=True)
    ap.add_argument("--readers", nargs="+", required=True, help="name=folder under <run>/runs/")
    ap.add_argument("--min-readers", type=int, default=2)
    ap.add_argument("--candidates", action="store_true", help="write <run>/candidates.json for the judge")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    run = args.run.resolve()
    readers = dict(r.split("=", 1) for r in args.readers)
    vocab = load_vocabulary()
    if args.candidates:
        cs = candidates(run, readers, args.min_readers, vocab)
        (run / "candidates.json").write_text(json.dumps(
            {"rule": f"at least {args.min_readers} of the readers that read the paper found the link",
             "readers": readers, "candidates": cs}, indent=1) + "\n")
        print(f"{len(cs)} candidates over {len({c['paper'] for c in cs})} papers")
        return 0
    text, stats = assemble(run, readers, args.min_readers, vocab)
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} differs from the stored readers and judge", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}: {stats}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
