"""Write docs/review/REVIEW.tex: the decisions the project lead must review.

Generated from the config files and the committed harvest outputs, so every
list and count in the report matches the repository. Compile with
`pdflatex` (twice, for the table of contents).

Usage::

    python scripts/build_review_report.py && (cd docs/review && pdflatex REVIEW.tex && pdflatex REVIEW.tex)
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from exposome_ehr.config import load_vocabulary  # noqa: E402

OUT = ROOT / "docs/review/REVIEW.tex"
ROLES = {
    "wild2005": "Defines the exposome concept (commentary)",
    "patel2010": "Agnostic EWAS method, NHANES, adults",
    "maitre2018": "HELIX: pediatric multi-exposure birth cohort",
    "vrijheid2020": "Pediatric exposome-wide study of obesity",
    "brokamp2018": "Geocoding environmental exposures onto EHR",
    "hu2023": "EHR exposome-wide study (OneFlorida)",
    "correa2022": "Neighbourhood factors and childhood asthma",
    "macdonald2014": "Vaccine as exposure, linked administrative data",
}
# Points in the vocabulary that are judgement calls, by facet id.
QUESTIONS = {
    "adhd_autism": "ADHD and autism share one facet. Split?",
    "neighborhood_deprivation": "Area-level SDOH is separate from household SDOH (next row). Keep split?",
    "childhood_cancer": "Only childhood cancer. Adult cancers are tagged nowhere.",
    "cardiometabolic": "Blood pressure, type 2 diabetes and lipids in one facet.",
    "prenatal_medication": "Only medicines in pregnancy or infancy. Adult drug exposures excluded.",
    "vaccination": "One facet for all vaccines. Split by vaccine type?",
    "healthcare_utilization": "Health care use as an outcome, not as a data source.",
    "tobacco_smoke": "Active and second-hand smoking together.",
    "mortality": "All-cause and cause-specific mortality together.",
}


def tex(s: str) -> str:
    s = " ".join(str(s).split())
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s.replace("≥", r"$\geq$").replace("–", "--").replace("—", "---").replace("→", r"$\to$")


def first_sentence(text: str, words: int = 22) -> str:
    first = re.split(r"(?<=[a-z0-9)])[.](?:\s|$)", " ".join(text.split()))[0]
    w = first.split()
    return " ".join(w[:words]) + ("..." if len(w) > words else "")


def tsv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


BOX = r"\decision"


def main() -> int:
    v = load_vocabulary()
    coding = yaml.safe_load((ROOT / "config/study_coding.yaml").read_text())
    counts = {r["facet_id"]: int(r["n_articles_any"]) for r in tsv(ROOT / "data/derived/facet_summary.tsv")}
    blocks = {r["block_id"]: r for r in tsv(ROOT / "data/derived/query_block_exclusivity.tsv")}
    papers = {r["pmid"]: r for r in tsv(ROOT / "extraction/2026-10-05-seeds/papers.tsv")}
    total = sum(1 for p in (ROOT / "data/articles").glob("*.jsonl") for _ in p.open())
    ages = {r["prenatal"] + r["infant"] + r["child"] + r["adolescent"]: 0 for r in tsv(ROOT / "data/derived/age_strata.tsv")}
    pediatric = sum(int(r["n_articles"]) for r in tsv(ROOT / "data/derived/age_strata.tsv")
                    if "1" in (r["prenatal"], r["infant"], r["child"], r["adolescent"]))
    del ages

    L: list[str] = []
    w = L.append
    w(r"""\documentclass[10pt]{article}
\usepackage[margin=2cm]{geometry}
\usepackage[T1]{fontenc}
\usepackage{lmodern,microtype,booktabs,longtable,array,xcolor,amssymb,enumitem,hyperref}
\hypersetup{colorlinks=true,linkcolor=blue!50!black,urlcolor=blue!50!black}
\setlist{nosep,leftmargin=1.4em}
\newcommand{\decision}[1]{\par\medskip\noindent\fcolorbox{orange!70!black}{orange!6}{\parbox{\dimexpr\linewidth-2\fboxsep-2\fboxrule}{\textbf{Decision.} #1\par\smallskip
$\square$ Approve as is \qquad $\square$ Change (note below) \qquad $\square$ Discuss\par\smallskip Notes: \hrulefill\par\vspace{1.2em}\hrulefill}}\par\medskip}
\newcolumntype{P}[1]{>{\raggedright\arraybackslash}p{#1}}
\title{Exposome / EHR rebuild: what needs your review}
\author{Branch \texttt{feature/decision-model-rebuild}, jeonglab-bcm/exposome-ehr-review}
\date{Generated by \texttt{scripts/build\_review\_report.py}, 2026-10-05}
\begin{document}
\maketitle
""")
    w(r"""\section*{Summary}
The repository was rebuilt on the POTS-phenotyping design: one broad PubMed query, facets as tags rather than
filters, and literature links found by decision models and confirmed by Claude with verbatim quotes.
The code is tested (132 offline tests) and the counts below are taken from the committed harvest. What only you
can decide are the four choices below. The model runs are built on Decisions~1 and~2, so changing those afterwards
means re-running; review them first.

\begin{center}\begin{tabular}{@{}clP{7.2cm}l@{}}\toprule
 & Decision & What to look at & Section\\\midrule
1 & Scope of the search & 4 query blocks; what is deliberately left out; 4 known misses & \ref{sec:scope}\\
2 & Seed papers & 8 papers the evidence graph is first built from & \ref{sec:seeds}\\
3 & Vocabulary & """ + f"{len(v.facet_list)}" + r""" terms in 6 groups; 9 flagged judgement calls & \ref{sec:vocab}\\
4 & Per-paper questions & """ + f"{len(coding['fields'])}" + r""" fields replacing the old checklist & \ref{sec:coding}\\\bottomrule
\end{tabular}\end{center}
""" + f"Corpus: {total:,} articles, {pediatric:,} tagged pediatric (prenatal, infant, child or adolescent). "
      + r"""Section~\ref{sec:skip} lists what does not need your review.
\tableofcontents
""")

    # ---------------------------------------------------------------- scope
    w(r"""\section{Decision 1: scope of the search}\label{sec:scope}
A paper enters the corpus if it matches any of the four blocks below (\texttt{config/query.yaml}). Nothing else is
filtered at search time: age, publication type and open access are recorded per paper and filtered later.

\begin{center}\begin{tabular}{@{}lP{8.6cm}rr@{}}\toprule
Block & What it retrieves & Papers & Only here\\\midrule
""")
    for b in v.profile_blocks("core"):
        r = blocks.get(b["id"], {})
        w(f"\\texttt{{{tex(b['id'])}}} & {tex(first_sentence(b['rationale'], 30))} & "
          f"{int(r.get('n_in_corpus', 0)):,} & {int(r.get('n_only_this_block', 0)):,}\\\\\n")
    w(r"""\bottomrule\end{tabular}\end{center}

\paragraph{Deliberately left out.}
\begin{itemize}
\item \textbf{Occupational exposure.} PubMed's ``Environmental Exposure'' heading includes it; 1,647 papers came in
only that way, so the heading is used without its children (maternal, prenatal and inhalation exposure are kept).
\item \textbf{Research-cohort studies with no routinely collected data}, unless they say ``exposome'' or are
exposome-wide (e.g.\ a single chemical in one birth cohort). The old pipeline included some of these.
\item \textbf{Vaccine uptake, coverage and hesitancy} studies (vaccination as the outcome, not the exposure);
excluded by title only.
\end{itemize}

\paragraph{Known misses and the widenings declined.} Of the old pipeline's 30 EHR-positive papers, 11 are retrieved;
15 of the other 19 are out of scope (2 corrections, 10 programme reports, descriptive surveillance or attitude
surveys, 2 research cohorts, 1 economic estimate). Four are real misses:
\begin{itemize}
\item PMC4997457 (air pollution and asthma exacerbations, Quebec administrative data): the abstract names only
``hospitalization or emergency room visit''. Adding such phrases grows the corpus to about 19,800, mostly aggregate
time-series studies.
\item PMC8986305 (vaccine safety comparison): adding surveillance and pharmacovigilance terms to the vaccine block
recovers it but adds about 1,600 papers.
\item PMC4381500 (mortality after DTP/MMR eligibility) and PMC4113360 (prenatal bereavement, registry data).
\end{itemize}
""")
    w(BOX + r"""{Are these the right boundaries? In particular: include occupational exposure? include single-exposure
research cohorts? accept the emergency-visit widening (+3,900 papers) or the vaccine-surveillance widening
(+1,600)?}
""")

    # ---------------------------------------------------------------- seeds
    w(r"""\section{Decision 2: seed papers}\label{sec:seeds}
The first model run reads these papers paragraph by paragraph; their links start the evidence graph, as POTS's seven
seeds did. Only CC BY text may be sent to the hosted Jev model, so most seeds rely on the local models agreeing.

\begin{center}\begin{tabular}{@{}lrP{5.6cm}lr@{}}\toprule
Seed & PMID & Role & Licence & Paragraphs\\\midrule
""")
    for key, ref in v.seed_references.items():
        p = papers.get(ref["expected_pmid"], {})
        lic = p.get("license", "")
        lic = ("CC BY" if "licenses/by/" in lic else "CC BY-NC" if "by-nc" in lic else "EHP" if "ehp" in lic
               else "author manuscript" if "text mining" in lic else "abstract only")
        w(f"{tex(key)} & {ref['expected_pmid']} & {tex(ROLES.get(key, ''))} & {lic} & {p.get('paragraphs', '0')}\\\\\n")
    w(r"""\bottomrule\end{tabular}\end{center}
Wild 2005 has no abstract in PubMed and no PMC full text, so it contributes no paragraphs; it stays a seed because
it defines the concept. The vocabulary's \texttt{source\_refs} were assigned from the seeds' abstracts, not yet
from reading them.
""")
    w(BOX + r"""{Keep these eight? Candidates to add: a pediatric EHR study of a chemical exposure (lead from EHR
screening results), a Vaccine Safety Datalink study with an open licence, and an adult EHR exposome-wide study
other than Hu 2023.}
""")

    # ---------------------------------------------------------------- vocab
    w(r"""\section{Decision 3: vocabulary}\label{sec:vocab}
Each term is a tag, not a category: a paper carries any number. ``Papers'' is how many corpus papers carry the tag
by either path (title/abstract query or NLM MeSH indexing). Rows marked \textbf{?} are judgement calls.
""")
    for gid, g in v.groups.items():
        w(f"\\subsection{{{tex(g['label'])}}}\n{tex(first_sentence(g['definition'], 40))}.\n\n")
        w(r"\begin{longtable}{@{}P{3.6cm}P{9.4cm}r@{}}\toprule Term & Definition (first sentence) & Papers\\\midrule\endhead" + "\n")
        for f in [f for f in v.facet_list if f["group"] == gid]:
            note = f"\\newline\\textbf{{?}} \\emph{{{tex(QUESTIONS[f['id']])}}}" if f["id"] in QUESTIONS else ""
            w(f"{tex(f['label'])} & {tex(first_sentence(f['definition']))}{note} & {counts.get(f['id'], 0):,}\\\\\n")
        w(r"\bottomrule\end{longtable}" + "\n")
    w(r"""\paragraph{Not in the vocabulary.} Diet and nutrition, physical activity, sleep, the microbiome, ionising
radiation, occupational exposures, adult cancers, and kidney or liver outcomes. Adding any of them is a new facet in
\texttt{config/facets.yaml}; papers are re-tagged without re-searching.
""")
    w(BOX + r"""{Approve the term lists? Mark terms to split, merge, rename or add. The flagged rows above are the
ones I was least sure of.}
""")

    # ---------------------------------------------------------------- coding
    w(r"""\section{Decision 4: per-paper questions}\label{sec:coding}
These replace the old free-text checklist (\texttt{config/study\_coding.yaml}). Each is a yes/no or a fixed set of
options, answered from the passages listed, with the probability and the paragraph that carried the answer kept.
Summary, key findings and limitations are no longer produced: they are not decisions.

\begin{center}\begin{longtable}{@{}lP{1.4cm}P{2.4cm}P{8.2cm}@{}}\toprule
Field & Type & Reads & Options\\\midrule\endhead
""")
    for name, spec in coding["fields"].items():
        if "options_from_group" in spec:
            opts = f"the {spec['options_from_group'].replace('_', ' ')} terms of Section~\\ref{{sec:vocab}}"
        elif "options" in spec:
            opts = tex("; ".join(spec["options"]))
        else:
            opts = "yes / no"
        w(f"\\texttt{{{tex(name)}}} & {tex(spec['type'].replace('_', ' '))} & {tex(', '.join(spec['read']))} & {opts}\\\\\n")
    w(r"""\bottomrule\end{longtable}\end{center}
\texttt{routinely\_collected\_data} keeps the old \texttt{ehr\_used} definition: electronic, individual-level and
collected for care, billing or administration before the study. Chart review by study staff, research questionnaires
and aggregate counts do not count. The pediatric EHR corpus is then: primary research = yes, routinely collected
data = yes, and age strata include infant, child or adolescent.
""")
    w(BOX + r"""{Are these the fields your review needs? Anything to add (e.g.\ sample size band, country, outcome
definition by codes vs.\ clinical measure, exposure window)? Is the \texttt{ehr\_used} definition still right?}
""")

    # ---------------------------------------------------------------- skip
    w(r"""\section{What does not need your review}\label{sec:skip}
\begin{itemize}
\item The harvester, parser, store and concept resolvers: ported from POTS-phenotyping with their tests.
\item The decision-model and Claude-judge code: tested offline with a fake model; also run end to end over the 255
seed paragraphs.
\item Derived tables (\texttt{data/derived/}) and the harvest report: generated; 24 of 26 checks pass. The two failures
are 19 terms with no OMOP concept match, mostly exposure concepts that the free SNOMED lookup does not cover; an
ATHENA vocabulary download fixes most of them.
\item The move of the old pipeline to \texttt{legacy/}.
\end{itemize}

\section*{After your review}
\begin{enumerate}
\item Apply your changes to the config files; re-harvest only if Decision 1 changed.
\item Run the seed reader run on the lab server and the Claude judge (\texttt{docs/DECISION\_MODELS.md}).
\item Hand-code 30--50 papers for the Decision 4 fields to measure agreement before the coding is used.
\item Before merging: the GitHub Pages site (old site moved to \texttt{legacy/docs/}), and the POTS branch this is
built on, which is not yet merged.
\end{enumerate}

\appendix
\section{Link predicates}
\begin{center}\begin{tabular}{@{}lP{4.2cm}P{7.8cm}@{}}\toprule Predicate & From $\to$ to & Question option\\\midrule
""")
    for p, spec in v.predicates.items():
        if p == "is_a":
            continue
        w(f"\\texttt{{{tex(p)}}} & {tex(', '.join(spec['domain']))} $\\to$ {tex(', '.join(spec['range']))} & {tex(spec['option'])}\\\\\n")
    w(r"""\bottomrule\end{tabular}\end{center}
\end{document}
""")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(L))
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
